/**
 * Haircut catalog used by the recommendation engine.
 * Face-shape guidance reflects common barber/stylist practice, not rules. Every option is a
 * suggestion with reasons; nothing is presented as the one correct cut.
 * Clipper guards: #1 ≈ 3 mm, #2 ≈ 6 mm, #3 ≈ 10 mm, #4 ≈ 13 mm.
 */
import type { FaceShape, HairDensity, HairLength, HairType, Level3, Sides, StylePresentation } from "../../types";

export type CutLength = "buzz" | "short" | "medium" | "long";

export interface Cut {
  id: string;
  name: string;
  presentations: StylePresentation[];
  length: CutLength;
  textures: HairType[];
  densities: HairDensity[];
  faceGood: FaceShape[];
  faceCareful: FaceShape[];
  /** Works well if the hairline is receding at the temples or uneven. */
  hairlineFriendly: boolean;
  maintenance: Level3;
  sides: Sides;
  rebookWeeks: [number, number];
  styleMinutes: number;
  /** Lengths in cm for the barber card. */
  topCm: [number, number];
  sides_: string;
  fringe: string;
  neckline: string;
  sideburns: string;
  temples: string;
  texture: string;
  finish: string;
  styling: string[];
  product: "clay" | "paste" | "pomade" | "sea-salt" | "curl-cream" | "leave-in" | "none";
  faceWhy: Partial<Record<FaceShape, string>>;
  carefulWhy: string;
}

export const CUTS: Cut[] = [
  {
    id: "buzz",
    name: "Buzz cut with a low fade",
    presentations: ["masculine", "neutral", "feminine"],
    length: "buzz",
    textures: ["straight", "wavy", "curly", "coily"],
    densities: ["thick", "medium", "fine"],
    faceGood: ["oval", "square", "diamond", "heart"],
    faceCareful: ["round"],
    hairlineFriendly: true,
    maintenance: "low",
    sides: "tight",
    rebookWeeks: [2, 3],
    styleMinutes: 0,
    topCm: [0.6, 1],
    sides_: "Low fade from #1 down to #0.5 or skin at the very bottom",
    fringe: "None, even length on top",
    neckline: "Tapered, not blocked",
    sideburns: "Faded into the sides",
    temples: "Follow your natural hairline; don't push it back",
    texture: "Even length, no texturizing",
    finish: "No product needed",
    styling: ["Wash and go.", "A light moisturizer on the scalp stops flaking."],
    product: "none",
    faceWhy: {
      oval: "Balanced proportions show well with very short hair.",
      square: "Puts the focus on a strong jaw.",
      diamond: "Keeps the silhouette clean around wider cheekbones.",
      heart: "Minimizes width at the top of the head.",
    },
    carefulWhy: "Very short hair shows head shape and can make a round face look rounder without some height on top.",
  },
  {
    id: "crew",
    name: "Textured crew cut",
    presentations: ["masculine", "neutral"],
    length: "short",
    textures: ["straight", "wavy", "curly", "coily"],
    densities: ["thick", "medium", "fine"],
    faceGood: ["oval", "square", "round", "diamond", "heart"],
    faceCareful: ["oblong"],
    hairlineFriendly: true,
    maintenance: "low",
    sides: "medium",
    rebookWeeks: [3, 5],
    styleMinutes: 2,
    topCm: [2, 3],
    sides_: "#2 on the sides, tapered to #1 at the neck",
    fringe: "Short, slightly forward",
    neckline: "Tapered",
    sideburns: "Short, tapered",
    temples: "Keep them natural; don't take them high",
    texture: "Point-cut the top for texture",
    finish: "Matte, natural",
    styling: ["Towel-dry.", "Rub a small amount of product through with fingers, pushing slightly forward or up."],
    product: "clay",
    faceWhy: {
      oval: "A clean, classic shape that suits balanced proportions.",
      square: "Keeps the lines sharp without competing with the jaw.",
      round: "Short sides reduce width at the cheeks.",
      diamond: "Tidy sides keep width at the cheekbones in check.",
      heart: "Short and even keeps the forehead area balanced.",
    },
    carefulWhy: "Short with volume on top can add length to an already long face.",
  },
  {
    id: "crop",
    name: "Textured crop with a fringe",
    presentations: ["masculine", "neutral"],
    length: "short",
    textures: ["straight", "wavy", "curly"],
    densities: ["thick", "medium", "fine"],
    faceGood: ["oblong", "heart", "diamond", "oval", "square"],
    faceCareful: ["round"],
    hairlineFriendly: true,
    maintenance: "low",
    sides: "tight",
    rebookWeeks: [3, 5],
    styleMinutes: 3,
    topCm: [4, 6],
    sides_: "Mid or low fade (#0.5 to #2). Go low if you want it softer",
    fringe: "Short fringe that sits about a finger's width above the brows",
    neckline: "Tapered",
    sideburns: "Faded",
    temples: "Keep them; the fringe softens the hairline",
    texture: "Heavily point-cut on top for separation",
    finish: "Matte and piecey",
    styling: ["Towel-dry, apply product, and push hair forward with fingers.", "Twist a few pieces for separation."],
    product: "clay",
    faceWhy: {
      oblong: "A forward fringe shortens the forehead visually.",
      heart: "The fringe softens a wider forehead.",
      diamond: "Adds width at the forehead to balance the cheekbones.",
      oval: "Easy, modern and suits balanced proportions.",
      square: "Texture softens angular features.",
    },
    carefulWhy: "A flat, straight-across fringe can make a round face look wider; keep it textured and short.",
  },
  {
    id: "quiff",
    name: "Short quiff with a taper",
    presentations: ["masculine", "neutral"],
    length: "short",
    textures: ["straight", "wavy"],
    densities: ["thick", "medium"],
    faceGood: ["round", "square", "oval"],
    faceCareful: ["oblong", "heart"],
    hairlineFriendly: false,
    maintenance: "medium",
    sides: "tight",
    rebookWeeks: [3, 5],
    styleMinutes: 5,
    topCm: [5, 8],
    sides_: "Taper from #2 down to #1, or a low fade",
    fringe: "Longest at the front, swept up and back",
    neckline: "Tapered",
    sideburns: "Tapered",
    temples: "Natural",
    texture: "Texturize the top, keep weight at the front",
    finish: "Natural hold, low shine",
    styling: ["Blow-dry the front up and back.", "Work a small amount of product through, lifting at the front."],
    product: "paste",
    faceWhy: {
      round: "Height on top and tight sides make the face look longer.",
      square: "Adds height that balances a strong jaw.",
      oval: "A classic look that suits balanced proportions.",
    },
    carefulWhy: "Height on top adds length and shows the temples, which may not suit a long face, a wide forehead or a receding hairline.",
  },
  {
    id: "side-part",
    name: "Classic side part",
    presentations: ["masculine", "neutral"],
    length: "short",
    textures: ["straight", "wavy"],
    densities: ["thick", "medium", "fine"],
    faceGood: ["oval", "round", "square", "oblong"],
    faceCareful: [],
    hairlineFriendly: false,
    maintenance: "medium",
    sides: "medium",
    rebookWeeks: [3, 5],
    styleMinutes: 5,
    topCm: [4, 6],
    sides_: "Scissor-over-comb or #3 tapered to #2",
    fringe: "Swept to the side",
    neckline: "Tapered",
    sideburns: "Medium, tidy",
    temples: "Natural",
    texture: "Light texturizing so the part sits naturally",
    finish: "Natural to light shine",
    styling: ["Find your natural part (where hair falls when wet).", "Comb or finger-style to the side with a small amount of product."],
    product: "pomade",
    faceWhy: {
      oval: "Polished and versatile.",
      round: "An asymmetric part adds angles.",
      square: "Classic lines complement a defined jaw.",
      oblong: "Side-swept hair adds width without height.",
    },
    carefulWhy: "A hard part can draw attention to one temple if the hairline is receding.",
  },
  {
    id: "slick-back",
    name: "Slicked-back medium length",
    presentations: ["masculine", "neutral"],
    length: "medium",
    textures: ["straight", "wavy"],
    densities: ["thick", "medium"],
    faceGood: ["oval", "square", "round"],
    faceCareful: ["oblong", "diamond", "heart"],
    hairlineFriendly: false,
    maintenance: "medium",
    sides: "medium",
    rebookWeeks: [4, 6],
    styleMinutes: 5,
    topCm: [8, 12],
    sides_: "#3 or scissor cut, slightly shorter than the top",
    fringe: "Long enough to comb back",
    neckline: "Tapered, slightly longer",
    sideburns: "Medium",
    temples: "Natural",
    texture: "Remove bulk but keep length",
    finish: "Low to medium shine",
    styling: ["Apply product to damp hair.", "Comb back and let it set; loosen with fingers for a softer look."],
    product: "pomade",
    faceWhy: {
      oval: "Shows off balanced proportions.",
      square: "Pairs well with strong angles.",
      round: "Height and backward direction lengthen the face.",
    },
    carefulWhy: "Pulling hair back exposes the forehead and temples, lengthening a long face and highlighting a receding hairline.",
  },
  {
    id: "curtains",
    name: "Middle part / curtain fringe",
    presentations: ["masculine", "neutral", "feminine"],
    length: "medium",
    textures: ["straight", "wavy"],
    densities: ["thick", "medium"],
    faceGood: ["oblong", "heart", "diamond", "oval"],
    faceCareful: ["round"],
    hairlineFriendly: true,
    maintenance: "medium",
    sides: "full",
    rebookWeeks: [5, 8],
    styleMinutes: 5,
    topCm: [10, 15],
    sides_: "Scissor cut, kept fuller, covering the top of the ears",
    fringe: "Long curtain fringe that splits at the center and reaches the cheekbones",
    neckline: "Natural, slightly longer",
    sideburns: "Covered by the sides",
    temples: "Covered by the fringe",
    texture: "Long layers for movement",
    finish: "Soft, natural",
    styling: ["Blow-dry with a center part, brushing each side out and back.", "A little sea-salt spray or light cream for texture."],
    product: "sea-salt",
    faceWhy: {
      oblong: "A fringe that frames the face shortens it visually.",
      heart: "Curtains soften a wider forehead.",
      diamond: "Adds width at the forehead and frames the cheekbones.",
      oval: "An easy, relaxed look for balanced proportions.",
    },
    carefulWhy: "A center part with fuller sides can add width to a round face.",
  },
  {
    id: "curly-taper",
    name: "Curly top with a low taper",
    presentations: ["masculine", "neutral"],
    length: "short",
    textures: ["wavy", "curly", "coily"],
    densities: ["thick", "medium", "fine"],
    faceGood: ["oval", "round", "square", "diamond", "oblong"],
    faceCareful: [],
    hairlineFriendly: true,
    maintenance: "low",
    sides: "tight",
    rebookWeeks: [3, 5],
    styleMinutes: 3,
    topCm: [4, 8],
    sides_: "Low taper or drop fade, #1 to #2",
    fringe: "Curls allowed to fall forward naturally",
    neckline: "Tapered",
    sideburns: "Tapered",
    temples: "Keep a soft line; avoid a sharp push-back line-up",
    texture: "Cut curls dry if possible so the shape is accurate",
    finish: "Defined curls, soft hold",
    styling: ["Apply leave-in and curl cream to soaking-wet hair.", "Scrunch and air-dry or diffuse. Don't brush once dry."],
    product: "curl-cream",
    faceWhy: {
      oval: "Natural texture with a clean outline.",
      round: "Volume on top with tight sides lengthens the face.",
      square: "Curls soften strong angles.",
      diamond: "Volume on top balances wider cheekbones.",
      oblong: "Keep the top moderate so curls add width rather than height.",
    },
    carefulWhy: "",
  },
  {
    id: "coily-top",
    name: "Coily top (twists or sponge curls) with a taper",
    presentations: ["masculine", "neutral"],
    length: "short",
    textures: ["coily", "curly"],
    densities: ["thick", "medium"],
    faceGood: ["oval", "round", "square", "diamond"],
    faceCareful: ["oblong"],
    hairlineFriendly: true,
    maintenance: "medium",
    sides: "tight",
    rebookWeeks: [2, 4],
    styleMinutes: 5,
    topCm: [3, 6],
    sides_: "Low or mid taper, #1 to #2",
    fringe: "Natural",
    neckline: "Tapered",
    sideburns: "Tapered",
    temples: "Soft line-up that follows your natural hairline",
    texture: "Even shape on top, rounded silhouette",
    finish: "Moisturized, defined",
    styling: ["Moisturize, then twist or use a sponge in circular motions.", "Protect at night with a durag or satin pillowcase."],
    product: "leave-in",
    faceWhy: {
      oval: "A clean, defined shape that suits balanced proportions.",
      round: "Height on top and tapered sides lengthen the face.",
      square: "Rounded top softens strong angles.",
      diamond: "Volume on top balances the cheekbones.",
    },
    carefulWhy: "Lots of height can make a long face look longer; keep the top moderate.",
  },
  {
    id: "flow",
    name: "Medium flow (swept back, tucked behind the ears)",
    presentations: ["masculine", "neutral"],
    length: "medium",
    textures: ["straight", "wavy"],
    densities: ["thick", "medium"],
    faceGood: ["oval", "square", "heart", "diamond"],
    faceCareful: ["oblong"],
    hairlineFriendly: false,
    maintenance: "low",
    sides: "full",
    rebookWeeks: [8, 10],
    styleMinutes: 3,
    topCm: [12, 18],
    sides_: "Scissor cut, long enough to tuck behind the ears",
    fringe: "Long, swept back or to the side",
    neckline: "Natural, left longer",
    sideburns: "Medium",
    temples: "Natural",
    texture: "Long layers to remove bulk",
    finish: "Natural movement",
    styling: ["Air-dry with a little sea-salt spray or light cream.", "Push back with fingers."],
    product: "sea-salt",
    faceWhy: {
      oval: "Suits balanced proportions and is easy to grow.",
      square: "Length softens a strong jaw.",
      heart: "Length at the sides balances a wider forehead.",
      diamond: "Covers the temples and adds width at the forehead.",
    },
    carefulWhy: "Long, flat hair can make a long face look longer; add volume at the sides.",
  },
  {
    id: "long-layers",
    name: "Long layers",
    presentations: ["feminine", "neutral", "masculine"],
    length: "long",
    textures: ["straight", "wavy", "curly", "coily"],
    densities: ["thick", "medium", "fine"],
    faceGood: ["round", "square", "oval", "heart", "diamond"],
    faceCareful: ["oblong"],
    hairlineFriendly: true,
    maintenance: "low",
    sides: "full",
    rebookWeeks: [8, 12],
    styleMinutes: 5,
    topCm: [30, 50],
    sides_: "Long, layers starting below the chin",
    fringe: "Optional face-framing pieces",
    neckline: "N/A",
    sideburns: "N/A",
    temples: "Face-framing layers can soften the temples",
    texture: "Long layers; ask for dusting of ends every 8–12 weeks",
    finish: "Soft movement",
    styling: ["Air-dry with a leave-in, or blow-dry with a round brush for volume.", "Keep heat below about 185°C / 365°F and use heat protectant."],
    product: "leave-in",
    faceWhy: {
      round: "Length below the chin lengthens the face.",
      square: "Layers around the jaw soften angles.",
      oval: "Versatile and low-maintenance.",
      heart: "Fullness from the jaw down balances a wider forehead.",
      diamond: "Layers at the chin add width below the cheekbones.",
    },
    carefulWhy: "Very long, straight hair can make a long face look longer; add curtain bangs or volume at cheek level.",
  },
  {
    id: "lob",
    name: "Lob (collarbone length)",
    presentations: ["feminine", "neutral"],
    length: "medium",
    textures: ["straight", "wavy", "curly"],
    densities: ["thick", "medium", "fine"],
    faceGood: ["round", "square", "heart", "oval", "oblong", "diamond"],
    faceCareful: [],
    hairlineFriendly: true,
    maintenance: "low",
    sides: "full",
    rebookWeeks: [6, 10],
    styleMinutes: 5,
    topCm: [20, 28],
    sides_: "Collarbone length, slightly longer at the front",
    fringe: "Optional side-swept or curtain fringe",
    neckline: "N/A",
    sideburns: "N/A",
    temples: "Optional fringe covers the temples",
    texture: "Soft internal layers",
    finish: "Loose waves or sleek",
    styling: ["Blow-dry or air-dry with a light cream.", "Loose waves with a flat iron add width for longer faces."],
    product: "leave-in",
    faceWhy: {
      round: "Length past the chin elongates the face.",
      square: "Falls below the jaw, softening it.",
      heart: "Adds fullness near the jaw.",
      oval: "Easy and flattering.",
      oblong: "With waves, adds width at the sides.",
      diamond: "Adds fullness at the jaw below wide cheekbones.",
    },
    carefulWhy: "",
  },
  {
    id: "bob",
    name: "Chin-length bob",
    presentations: ["feminine", "neutral"],
    length: "medium",
    textures: ["straight", "wavy"],
    densities: ["medium", "fine", "thick"],
    faceGood: ["oval", "heart", "oblong", "diamond"],
    faceCareful: ["round", "square"],
    hairlineFriendly: true,
    maintenance: "medium",
    sides: "full",
    rebookWeeks: [5, 8],
    styleMinutes: 5,
    topCm: [15, 20],
    sides_: "Ends just at or below the chin",
    fringe: "Optional",
    neckline: "N/A",
    sideburns: "N/A",
    temples: "N/A",
    texture: "Blunt or softly layered",
    finish: "Sleek or tousled",
    styling: ["Blow-dry smooth, or scrunch with texture spray."],
    product: "sea-salt",
    faceWhy: {
      oval: "A crisp shape that suits balanced proportions.",
      heart: "Adds width at the chin.",
      oblong: "Width at the sides shortens a long face.",
      diamond: "Fullness at the chin balances the cheekbones.",
    },
    carefulWhy: "Ending exactly at the jaw repeats its width, which can emphasize a round or square jaw; go a little longer.",
  },
  {
    id: "curly-shag",
    name: "Shaped curls (curly shag)",
    presentations: ["feminine", "neutral", "masculine"],
    length: "medium",
    textures: ["wavy", "curly", "coily"],
    densities: ["thick", "medium"],
    faceGood: ["oval", "round", "square", "heart", "oblong"],
    faceCareful: [],
    hairlineFriendly: true,
    maintenance: "low",
    sides: "full",
    rebookWeeks: [8, 12],
    styleMinutes: 5,
    topCm: [10, 20],
    sides_: "Layered curls, cut dry curl by curl if your stylist offers it",
    fringe: "Curly fringe optional",
    neckline: "N/A",
    sideburns: "N/A",
    temples: "Curls frame the temples",
    texture: "Layered for shape and bounce",
    finish: "Defined curls",
    styling: ["Leave-in and curl cream on wet hair.", "Diffuse or air-dry; refresh with water spray on day two."],
    product: "curl-cream",
    faceWhy: {
      oval: "Shows off natural texture.",
      round: "Height from layers lengthens the face.",
      square: "Curls soften the jaw.",
      heart: "Volume around the jaw balances the forehead.",
      oblong: "Width from curls balances length.",
    },
    carefulWhy: "",
  },
  {
    id: "pixie",
    name: "Textured pixie",
    presentations: ["feminine", "neutral"],
    length: "short",
    textures: ["straight", "wavy"],
    densities: ["fine", "medium"],
    faceGood: ["oval", "heart", "diamond"],
    faceCareful: ["round", "square"],
    hairlineFriendly: true,
    maintenance: "medium",
    sides: "tight",
    rebookWeeks: [4, 6],
    styleMinutes: 5,
    topCm: [4, 8],
    sides_: "Short and soft around the ears",
    fringe: "Side-swept, textured",
    neckline: "Tapered",
    sideburns: "Soft",
    temples: "Fringe softens the temples",
    texture: "Point-cut for texture",
    finish: "Piecey",
    styling: ["A small amount of paste, piece out the fringe."],
    product: "paste",
    faceWhy: {
      oval: "Highlights balanced features.",
      heart: "Side-swept fringe balances the forehead.",
      diamond: "Shows off cheekbones with a softened hairline.",
    },
    carefulWhy: "Very short with no height can make a round or square face look wider; add height and a side-swept fringe.",
  },
];

export const PRODUCT_LABEL: Record<Cut["product"], string> = {
  clay: "Matte clay",
  paste: "Styling paste",
  pomade: "Water-based pomade",
  "sea-salt": "Sea-salt / texture spray",
  "curl-cream": "Curl cream",
  "leave-in": "Leave-in conditioner",
  none: "No product",
};

export const LENGTH_ORDER: CutLength[] = ["buzz", "short", "medium", "long"];
export const desiredToCut: Record<HairLength, CutLength[]> = {
  short: ["short", "buzz"],
  medium: ["medium"],
  long: ["long"],
};
